runtime: nodejs20
service: default  
entrypoint: npm start

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  ACCESS_TOKEN_SECRET: "fa71042126d8287538"
  DB_HOST: "34.89.121.129"              # Cloud SQL Public IP
  DB_PORT: "3306"
  DB_USERNAME: "khazna-vacation"
  DB_PASSWORD: "Khazna2024"
  DB_DATABASE: "khazna-db"
  EMAIL_USER: "saifahmedsalah11@gmail.com"
  EMAIL_PASSWORD: "lsssmezaheetgmld"
  SuperAdminName: "Saif Ahmed"
  SMTP_HOST: "smtp.khazna.app"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"


health_check:
  enable_health_check: False
