steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args: ['-c', 'npm install']

- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args: ['-c', 'ls -la node_modules/.bin/'] # Check file permissions

- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args: ['-c', 'npx tsc --version'] # Check if tsc can be executed

- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args: ['-c', 'npx tsc'] # Use npx to run tsc

- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args: ['-c', 'npm start']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'SERVICE_NAME', '--image', 'gcr.io/$PROJECT_ID/IMAGE_NAME', '--platform', 'managed']

options:
  logging: CLOUD_LOGGING_ONLY # Or use other logging options as needed
