steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '-g', 'typescript@5.5.3', '--save-dev']
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'bash'
  script: |
    tsc
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']

options:
  logging: CLOUD_LOGGING_ONLY
  env:
  - TSC_USER_ENABLED=1
