steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/khazna-434418/api-image:$SHORT_SHA', '.']

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/khazna-434418/api-image:$SHORT_SHA']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-service'  # Change this to your Cloud Run service name
      - '--image=gcr.io/khazna-434418/api-image:$SHORT_SHA'
      - '--platform=managed'
      - '--region=us-central1'  # Change this to your preferred region
      - '--allow-unauthenticated'

substitutions:
  _DEPLOY_REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging only
