steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']  # Installs all dependencies from package.json

# If your build script is a custom shell script named 'build.sh':
- name: 'bash'
  args: ['./build.sh']  # Replace with the path to your build script

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']  # Assuming build script is defined in package.json

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']

options:
  logging: CLOUD_LOGGING_ONLY