steps:
  # Step 1: Install TypeScript globally
  - name: 'node:20'
    args: ['npm', 'install', '-g', 'typescript']

  # Step 2: Compile TypeScript using the globally installed tsc
  - name: 'node:20'
    args: ['tsc', '--outDir', 'dist']

  # Step 3: Deploy the application using gcloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - TSC_USER_ENABLED=1
    - NPM_CONFIG_LOGLEVEL=verbose  # Enable verbose logging for npm to troubleshoot issues
