steps:
- name: 'node:16'
  args: ['npm', 'install', '-g', 'typescript@5.5.3', '--production']
- name: 'node:16'
  args: ['npm', 'run', 'tsc']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'tsc', '--outDir', 'dist']  # Compile TypeScript to a 'dist' directory
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  

options:
  logging: CLOUD_LOGGING_ONLY
  env:
  - TSC_USER_ENABLED=1
