steps:
  # Build the application
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}', '.']

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}']

  # Deploy to Google App Engine
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - '--image=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}'
      - '--platform=managed'
      - '--region=${_REGION}'
      - '--cluster=${_CLUSTER}'
      - '--namespace=${_NAMESPACE}'

  # Deploy to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}
      - --platform=managed
      - --region=${_REGION}

options:
  substitution:
    _SERVICE_NAME: 'my-service'
    _REGION: 'us-central1'
    _CLUSTER: 'my-cluster'
    _NAMESPACE: 'my-namespace'