steps:
  # Step 1: Install TypeScript locally (instead of globally)
  - name: 'node:20'
    args: ['npm', 'install']

  # Step 2: Make sure the local tsc is executable (if needed, skip if not required)
  - name: 'node:20'
    entrypoint: 'chmod'
    args: ['+x', './node_modules/.bin/tsc']

  # Step 3: Run the local tsc using npx to compile TypeScript to a 'dist' directory
  - name: 'node:20'
    args: ['npx', 'tsc', '--outDir', 'dist']

  # Step 4: Create a deployable package using tar
  - name: 'gcr.io/cloud-builders/pack'
    args: ['--path=dist', '--filename=dist.tar.gz', '--destination=./']

  # Step 5: Deploy the application using gcloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--runtime=nodejs20']

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - NPM_CONFIG_LOGLEVEL=verbose  # Enable verbose logging for npm to troubleshoot issues