steps:
- name: 'gcr.io/cloud-builders/npm'  # Install dependencies (with force)
  args: ['install', '--force']
- name: 'gcr.io/cloud-builders/npm'  # Build for production
  args: ['run', 'build', '--prod']

- name: 'gcr.io/cloud-builders/gcloud'  # Deploy the application
  args: ['app', 'deploy']
  # Assuming deployment configuration is already set up in gcloud

options:
  logging: CLOUD_LOGGING_ONLY  # Only log to Cloud Logging