steps:
  - name: 'node:20'  # Install dependencies
    args: ['npm', 'install']  

  - name: 'node:20'  # Run build script (assuming it exists)
    args: ['npm', 'run', 'build']

  - name: 'gcr.io/cloud-builders/gcloud'  # Deploy the application
    args: ['app', 'deploy']

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - TSC_USER_ENABLED=1
    - NPM_CONFIG_LOGLEVEL=verbose  # Enable verbose logging for npm (optional)