steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Run tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

# Configure logging (choose the appropriate option)
build_options:
  logging: NONE  # No logs (not recommended for production)
  # OR
  logging: CLOUD_LOGGING_ONLY  # Logs only sent to Cloud Logging (limited details)
  # OR (if you have a GCS bucket for logs)
  # logging: REGIONAL_USER_OWNED_BUCKET  # Cloud B