steps:
- name: 'node:16'
  args: ['npm', 'install']
- name: 'node:16'
  args: ['npm', 'run', 'build']  # Assuming your build script is named "build"
- name: 'node:16'
  args: ['npm', 'install', 'typescript']  # Install TypeScript compiler
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']

options:
  logging: CLOUD_LOGGING_ONLY