steps:
  - name: 'gcr.io/cloud-builders/node'
    args: ['npm', 'install']
  - name: 'gcr.io/cloud-builders/node'
    args: ['npm', 'run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

options:
  logging: CLOUD_LOGGING_ONLY