steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args: ['-c', 'npm install']

- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args: ['-c', 'npm run build'] # Ensure the build script is defined and works

- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args: ['-c', 'npm start'] # Make sure this command starts your application correctly

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'SERVICE_NAME', '--image', 'gcr.io/$PROJECT_ID/IMAGE_NAME', '--platform', 'managed']

# Optional logging configuration
options:
  logging: CLOUD_LOGGING_ONLY # Or use other logging options as needed
