steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']  # Installs project dependencies

- name: 'gcr.io/cloud-builders/npm'
  args: ['test']  # Runs your project's tests
  # Handle potential test errors:
  entrypoint: npm  # Use npm as the entrypoint for the step
  # (Optional) Manage failures gracefully:
  #   - Exit with a non-zero status code (e.g., `exit 1`) to trigger build failure

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']  # Deploys to App Engine

options:
  logging: CLOUD_LOGGING_ONLY  # Configures logging for Cloud Logging only