steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Run tests (assuming your test script is named 'test.js')
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test', 'main.ts']  # Replace 'test.js' with your actual test script name

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

# Configure logging (choose the appropriate option)
options:
  logging: CLOUD_LOGGING_ONLY  # Logs only sent to Cloud Logging (limited details)
  # OR (if you have a GCS bucket for logs)
  # logging: REGIONAL_USER_OWNED_BUCKET  # Cloud B