steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']  # Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']  # Run your build command

options:
  logging: CLOUD_LOGGING_ONLY