steps:
  - name: 'node:20'  # Step to install dependencies
    args: ['npm', 'install']

  - name: 'node:20'  # Step to run the TypeScript compiler
    args: ['npm', 'run', 'build']

  - name: 'gcr.io/cloud-builders/gcloud'  # Step to deploy the application
    args: ['app', 'deploy']

options:
  logging: CLOUD_LOGGING_ONLY  # Only log to Cloud Logging
  env:
    - TSC_USER_ENABLED=1  # Example environment variable
    - NPM_CONFIG_LOGLEVEL=verbose  # Enable verbose logging for npm
