steps:
- name: 'node:16'
  args: ['npm', 'install', '-g', 'typescript@5.5.3', '--production']
- name: 'node:16'
  args: ['npm', 'run', 'tsc']
options:
  cache:
    paths: ['/root/.npm']
  logging: VERBOSE